In [2]:
import pandas as pd
import numpy as np
import joblib

In [3]:
league_model = joblib.load("League_Predictions.pkl")
knockout_model = joblib.load("KnockOut_Predictions.pkl")
col_names = joblib.load("col_names.pkl")

C:\Users\Solo\anaconda3\envs\DeepLearning\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [38]:
Team1 = "Uruguay"
Team2 = "Brazil"
Team1_FIFA_RANK = 10
Team2_FIFA_RANK = 1
Team1_Goalkeeper_Score = 80
Team2_Goalkeeper_Score = 89
Team1_Defense = 81
Team1_Offense = 84
Team1_Midfield = 80
Team2_Defense = 85
Team2_Offense = 86
Team2_Midfield = 85

In [39]:
list_value = [[Team1, Team2, Team1_FIFA_RANK, Team2_FIFA_RANK, Team1_Goalkeeper_Score, Team2_Goalkeeper_Score, Team1_Defense, Team1_Offense, Team1_Midfield, Team2_Defense, Team2_Offense, Team2_Midfield]]

In [40]:
list_value

[['Uruguay', 'Brazil', 10, 1, 80, 89, 81, 84, 80, 85, 86, 85]]

In [41]:
df = pd.DataFrame(data=list_value,columns=col_names)

In [42]:
df

Team1   Team2  Team1_FIFA_RANK  Team2_FIFA_RANK  Team1_Goalkeeper_Score  \
0  Uruguay  Brazil               10                1                      80   

   Team2_Goalkeeper_Score  Team1_Defense  Team1_Offense  Team1_Midfield  \
0                      89             81             84              80   

   Team2_Defense  Team2_Offense  Team2_Midfield  
0             85             86              85

In [43]:
league_model.predict(df)

array([0], dtype=int64)

In [44]:
knockout_model.predict(df)

array([0], dtype=int64)

In [45]:
knockout_model.predict_proba(df)

array([[0.69, 0.31]])